<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-44HO9DI" failures="1" tests="1" name="SeleniumProject" time="0.067" errors="0" timestamp="2024-10-02T13:16:11 IST">
  <testcase classname="com.automation.testng.LoginTest" name="verifyUserCannotLoginWithInvalidCred" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [110] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [110] but found [10]
at com.automation.testng.LoginTest.verifyUserCannotLoginWithInvalidCred(LoginTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCannotLoginWithInvalidCred -->
  <testcase classname="com.automation.testng.LoginTest" name="verifyUserCanLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="com.automation.testng.LoginTest" name="verifyUserCanLogout" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserCanLogout -->
</testsuite> <!-- SeleniumProject -->
